--DAY07--------------------------

--@DQL종합실습문제
--1. 기술지원부에 속한 사람들의 사람의 이름,부서코드,급여를 출력하시오.
SELECT EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
WHERE DEPT_TITLE = '기술지원부';

--2. 기술지원부에 속한 사람들 중 가장 연봉이 높은 사람의 이름,부서코드,급여를 출력하시오
SELECT EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID 
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID WHERE DEPT_TITLE = '기술지원부');

--3. 매니저가 있는 사원중에 월급이 전체사원 평균을 넘고 
--사번,이름,매니저 이름, 월급을 구하시오.
SELECT EMP_ID, EMP_NAME, (SELECT EMP_NAME FROM EMPLOYEE WHERE EMP_ID=E.MANAGER_ID)"매니저 이름", SALARY
FROM EMPLOYEE E
WHERE MANAGER_ID IS NOT NULL;

--매니저가 있는 사원 중 월급이 전체평균 넘는 직원의 사번 이름 매니저이름 월급 출력
SELECT EMP_ID, EMP_NAME
,(SELECT EMP_NAME FROM EMPLOYEE WHERE EMP_ID = E.MANAGER_ID) AS "매니저 이름", SALARY
FROM EMPLOYEE E
WHERE MANAGER_ID IS NOT NULL AND SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE);

-- 사원번호    사원명     월급    평균월급    월급-평균월급
SELECT EMP_ID, EMP_NAME, SALARY, AVG_SAL 평균월급, SALARY - AVG_SAL 월급차
FROM EMPLOYEE
CROSS JOIN (SELECT ROUND(AVG(SALARY)) "AVG_SAL" FROM EMPLOYEE);

-- 양수에 '+' 표시하기
SELECT EMP_ID, EMP_NAME, SALARY, AVG_SAL 평균월급
,(CASE WHEN SALARY - AVG_SAL>0 THEN '+'END)||(SALARY - AVG_SAL)월급차
FROM EMPLOYEE
CROSS JOIN (SELECT ROUND(AVG(SALARY)) "AVG_SAL" FROM EMPLOYEE);










