CREATE TABLE STUDENT_TBL (
    STUDENT_ID VARCHAR2(15),
    STUDENT_PWD VARCHAR2(15),
    STUDENT_NAME VARCHAR2(20),
    GENDER CHAR(1),
    AGE NUMBER,
    EMAIL VARCHAR2(30),
    PHONE CHAR(11),
    ADDRESS VARCHAR2(500),
    HOBBY VARCHAR2(50),
    ENROLL_DATE DATE
);
ALTER TABLE STUDENT_TBL
ADD CONSTRAINT STUDENT_PK PRIMARY KEY(STUDENT_ID);
ALTER TABLE STUDENT_TBL
ADD CHECK(GENDER IN('M','F'));
ALTER TABLE STUDENT_TBL
MODIFY AGE NOT NULL;
ALTER TABLE STUDENT_TBL
MODIFY STUDENT_NAME NOT NULL;
ALTER TABLE STUDENT_TBL
MODIFY STUDENT_PWD NOT NULL;
--NOT NULL : MODIFY로 추가


INSERT INTO STUDENT_TBL
VALUES('ADMIN','ADMIN','관리자','M',30,'admin@iei.or.kr',
'01012345678','서울시 중구','독서 운동',SYSDATE);
COMMIT;
--커밋해야 jdbc에 넘어간다! 커밋 필수
INSERT INTO STUDENT_TBL
VALUES('aaa','aaa','에이','M',21,'aaa@iei.or.kr',
'01012345888','서울시 광진구','요가',SYSDATE);
INSERT INTO STUDENT_TBL
VALUES('khuser01', 'pass01', '일용자', 'M', 21,'khuser01@kh.com',
'01092920303', '서울시 종로구', '수영,걷기', SYSDATE);
COMMIT;

select * from STUDENT_TBL;

----------------------------------------------------------

CREATE TABLE MEMBER_TBL(
    MEMBER_ID VARCHAR2(20),
    MEMBER_PWD VARCHAR2(30),
    MEMBER_NAME VARCHAR2(20),
    MEMBER_GENDER VARCHAR2(3),
    MEMBER_AGE NUMBER,
    MEMBER_EMAIL VARCHAR2(30),
    MEMBER_PHONE VARCHAR2(15),
    MEMBER_ADDRESS VARCHAR2(100),
    MEMBER_HOBBY VARCHAR2(50),
    MEMBER_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

--ID PK / PWD NOT NULL / NAME NN / GEN CHECK

ALTER TABLE MEMBER_TBL
ADD CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_ID);
ALTER TABLE MEMBER_TBL
ADD CHECK(MEMBER_GENDER IN('여','남'));
ALTER TABLE MEMBER_TBL
MODIFY MEMBER_PWD NOT NULL;
ALTER TABLE MEMBER_TBL
MODIFY MEMBER_NAME NOT NULL;

SELECT * FROM USER_CONSTRAINTS;

INSERT INTO MEMBER_TBL
VALUES ('ADMIN','ADMIN','관리자','여',25,'mail@mail','010-1234-1223','서울시 중구','검도',DEFAULT);
COMMIT;


SELECT COUNT(*) AS M_COUNT FROM MEMBER_TBL WHERE MEMBER_ID = 'admin' AND MEMBER_PWD = 'admin';
--로그인 하기 위해, 조건에 맞는 한명 찾는 것

