--DAY06----------------------------------------
--1. 전지연 직원의 관리자 이름을 출력하라
--전지연의 관리자ID 찾기-> 관리자ID로 직원 이름 구하기
SELECT EMP_NAME
FROM EMPLOYEE
WHERE EMP_ID = (SELECT MANAGER_ID FROM EMPLOYEE WHERE EMP_NAME = '전지연');

--2. 전 직원의 평균 급여보다 많은 급여를 받고 있는 직원의 사번, 이름, 직급코드, 급여를 조회하시오
--평균 급여를 구한다 -> 평균급여보다 많은 급여를 받는 직원을 조회
SELECT EMP_ID, EMP_NAME, JOB_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE);

--EX1 송중기, 박나라의 부서에 속한 사원 정보 출력
SELECT EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE IN (SELECT DEPT_CODE FROM EMPLOYEE WHERE EMP_NAME IN ('송중기','박나라'));

--EX2 차태현, 전지연 사원의 급여등급(sal_level)과 같은 사원의 직급명, 사원명을 출력.
SELECT EMP_NAME, JOB_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE SAL_LEVEL IN (SELECT SAL_LEVEL FROM EMPLOYEE WHERE EMP_NAME IN ('차태연','전지연'));

--EX3 ASIA1 지역에 근무하는 사원의 부서코드, 사원명
--JOIN 사용
SELECT EMP_NAME, DEPT_CODE
FROM EMPLOYEE
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
JOIN LOCATION ON LOCATION_ID = LOCAL_CODE
WHERE LOCAL_NAME = 'ASIA1';

--EX 직급이 대표, 부사장이 아닌 모든 사원을 부서별로 출력
SELECT DEPT_CODE, EMP_NAME
FROM EMPLOYEE
WHERE JOB_CODE NOT IN (SELECT JOB_NAME FROM JOB WHERE JOB_NAME IN ('대표','부사장'))
ORDER BY 1;

--EX1 부하직원이 한명이라도 있는 직원 출력
SELECT EMP_NAME, SALARY
FROM EMPLOYEE E
WHERE EXISTS (SELECT 1 FROM EMPLOYEE WHERE MANAGER_ID=E.EMP_ID);

--EX2 DEPT_CODE가 없는 사람 출력(상관 서브쿼리로)
SELECT EMP_NAME, SALARY
FROM EMPLOYEE E
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENT WHERE DEPT_ID = E.DEPT_CODE);

--EX3 가장 많은 급여를 받는 사원(상관 서브쿼리로)
SELECT EMP_NAME, SALARY
FROM EMPLOYEE E
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEE WHERE SALARY > E.SALARY);

--EX4 직급이 J1, J2, J3이 아닌 사원중에서 자신의 부서별 평균급여보다 많은 급여를 받는 사원출력.
-- 부서코드, 사원명, 급여, 부서별 급여평균
SELECT E.EMP_NAME, E.DEPT_CODE, E.SALARY, AVG_SAL
FROM EMPLOYEE E
JOIN (SELECT DEPT_CODE, ROUND(AVG(SALARY)) "AVG_SAL" FROM EMPLOYEE
GROUP BY DEPT_CODE) A ON E.DEPT_CODE = A.DEPT_CODE
WHERE JOB_CODE NOT IN ('J1','J2','J3') AND E.SALARY > AVG_SAL;

--EX 사원명 부서명 부서별 평균임금을 스칼라 서브쿼리로 출력 
SELECT EMP_NAME, DEPT_CODE, (SELECT ROUND(AVG(SALARY)) FROM EMPLOYEE 
WHERE DEPT_CODE = D.DEPT_ID) "부서 평균임금"
FROM EMPLOYEE
JOIN DEPARTMENT D ON DEPT_CODE = DEPT_ID;

--EX1 2010년도에 입사한 사원의 사번, 사원명, 입사년도를 인라인뷰를 사용해서 출력.
SELECT *
FROM (SELECT EMP_ID, EMP_NAME, EXTRACT(YEAR FROM HIRE_DATE) 입사년도 FROM EMPLOYEE) 
WHERE 입사년도 BETWEEN 2010 AND 2019;

--EX2 사원중 30대, 40대인 여자사원의 사번, 부서명, 성별, 나이를 인라인뷰를 사용해서 출력하라.
SELECT *
FROM (SELECT EMP_ID, DEPT_TITLE, DECODE(SUBSTR(EMP_NO,8,1),'1','남','2','여') 성별, 
EXTRACT(YEAR FROM SYSDATE) - (1900+TO_NUMBER(SUBSTR(EMP_NO,1,2))) 나이
FROM EMPLOYEE JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID)
WHERE 성별 = '여' AND 나이 BETWEEN 30 AND 49; 



